services:
  # Service 1 — Rotation automatique LNRC (Node.js)
  - type: worker
    name: lnrc-rotation
    runtime: node
    rootDir: ./rotation-js
    plan: free
    buildCommand: npm ci --omit=dev
    startCommand: npm start
    envVars:
      - key: RPC_URL
        sync: false
      - key: TOKEN_ADDRESS
        sync: false
      - key: CHAIN_ID
        sync: false
      - key: TOKEN_DECIMALS
        sync: false
      - key: TOKEN_TAX_RATE
        sync: false
      - key: TOKEN_GROSS_UP
        sync: false
      - key: WALLET_1_PRIVKEY
        sync: false
      - key: WALLET_2_PRIVKEY
        sync: false
      - key: WALLET_3_PRIVKEY
        sync: false
      - key: WALLET_4_PRIVKEY
        sync: false
      - key: AMOUNT_TOKEN_PER_TX
        sync: false
      - key: AMOUNT_JITTER_PCT
        sync: false
      - key: NUM_TX_PER_DAY
        sync: false
      - key: MIN_TOKEN_BALANCE
        sync: false
      - key: DISCORD_WEBHOOK_URL
        sync: false

  # Service 2 — IA Monitoring LNRC (Python)
  - type: worker
    name: lnrc-ai-monitor
    runtime: python
    rootDir: ./ai
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python ai_volume_analyzer.py
    envVars:
      - key: RPC_URL
        sync: false
      - key: CONTRACT_ADDRESS
        sync: false
      - key: CHAIN_ID
        sync: false
      - key: POLL_SECONDS
        value: 30
      - key: ALERT_THRESHOLD_USD
        value: "5000"
      - key: DISCORD_WEBHOOK_URL
        sync: false
