services:
  - type: web
    name: lnrc-telegram-bot
    env: python
    repo: https://github.com/raouldecasa/lnrc-rotation
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python bot/bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: RPC_URL
        sync: false
      - key: CONTRACT_ADDRESS
        sync: false
    plan: free
    autoDeploy: true
